### ISSUE TITLE
Don't export `@set`

### ISSUE THREAD

**Issue by jariji** [JuliaFolds2/OhMyThreads.jl#115]
`OhMyThreads.@set` is pretty niche functionality and it clashes with `Accessors.@set`. Currently it's exported, would it be okay to not export it?

**Comment by carstenbauer** [comment]
It's not at all niche if you use the `@tasks` macro API. I would recommend that you only explicitly import/`using` the bits that you need rather then just doing `using OhMyThreads`.

While the simple `using X` is, unfortunately, very common in Julia codes, it is quite generally an anti-pattern that doesn't scale well. (Any export that a package might add over time could break your code, because clashes like the one you mention here could occur.)
